databases:
  - name: party_jukebox_db
    databaseName: party_jukebox_prod
    user: party_jukebox

services:
  - type: web
    name: party-jukebox
    runtime: docker
    plan: free
    preDeployCommand: "./bin/migrate"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: party_jukebox_db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: POOL_SIZE
        value: 2
